name: joshbyers
favicon: null
layout_spectrum: 0.36627
typography_spectrum: 0.36932
title: Josh Byers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161920'
    - '#595451'
    - '#da9051'
    - '#ffca88'
    - '#b56717'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
